In [1]:
import pandas as pd

In [7]:
info = {
    "Name"  : ["Ruchira", "Ash", "Amey"],
    "CGPA"  : [9.5, 9.6, 9.9]
}
df =pd.DataFrame(info)
print(df)

      Name  CGPA
0  Ruchira   9.5
1      Ash   9.6
2     Amey   9.9

In [8]:
df

      Name  CGPA
0  Ruchira   9.5
1      Ash   9.6
2     Amey   9.9

In [9]:
s = pd.Series([1,2,3,4,5])
print(s)
print(type(s))

#access index
print(s[0])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1

In [11]:
s = pd.Series([11,33,44,55], index =["dfs" , "ddv", "gf", "bujb"])
print(s)

print(s["dfs"])

dfs     11
ddv     33
gf      44
bujb    55
dtype: int64
11

In [14]:
#csv data
df = pd.read_csv("employee_data.csv")
print(df, type(df))

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0 <class 'pandas.core.frame.DataFrame'>

In [20]:
#methods

df.head()  # first 5 rows
df.tail()
df.sample()
df.info()
df.shape()

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

TypeError: 'tuple' object is not callable

In [21]:
df.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [17]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [16]:
#json data
df = pd.read_json("employee_data.json")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [26]:
#  AQI DATASET
df = pd.read_csv("global_air_quality.csv")
df

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
0,Bangkok,Thailand,2023-03-19,86.57,25.19,99.88,30.63,4.46,36.29,17.67,59.35,13.76
1,Istanbul,Turkey,2023-02-16,50.63,97.39,48.14,8.71,3.40,144.16,3.46,67.51,6.36
2,Rio de Janeiro,Brazil,2023-11-13,130.21,57.22,98.51,9.92,0.12,179.31,25.29,29.30,12.87
3,Mumbai,India,2023-03-16,119.70,130.52,10.96,33.03,7.74,38.65,23.15,99.97,7.71
4,Paris,France,2023-04-04,55.20,36.62,76.85,21.85,2.00,67.09,16.02,90.28,14.16
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Johannesburg,South Africa,2023-09-16,147.85,184.34,90.33,34.93,2.81,191.45,-1.92,65.22,15.48
9996,Berlin,Germany,2023-12-05,12.22,121.49,49.04,5.66,2.10,184.56,-9.81,12.16,10.75
9997,Moscow,Russia,2023-11-26,44.07,143.62,8.41,32.58,0.69,167.68,39.35,53.95,4.56
9998,Berlin,Germany,2023-02-03,67.43,96.79,43.23,29.19,6.01,148.50,26.21,58.54,2.71
9999,Bangkok,Thailand,2023-06-13,16.34,28.80,50.48,21.20,0.49,17.41,2.50,66.05,5.01

In [27]:
df.describe()

,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000
mean,77.448439,104.438161,52.198649,25.344490,5.047984,106.031643,14.89715,55.078579,10.231636
std,41.927871,55.062396,27.320490,14.091194,2.852625,55.081345,14.44380,25.982232,5.632628
min,5.020000,10.000000,5.010000,1.000000,0.100000,10.040000,-10.00000,10.010000,0.500000
25%,41.185000,57.137500,28.347500,13.190000,2.560000,58.380000,2.25750,32.527500,5.290000
50%,77.725000,103.690000,52.100000,25.350000,5.090000,106.055000,14.75500,55.080000,10.260000
75%,113.392500,152.265000,75.705000,37.500000,7.480000,153.982500,27.38250,77.442500,15.070000
max,149.980000,200.000000,100.000000,49.990000,10.000000,200.000000,40.00000,99.990000,20.000000

In [3]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("global_air_quality.csv")

In [4]:
# basic dataframe checking
# first 5 rows
df.head()

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
0,Bangkok,Thailand,2023-03-19,86.57,25.19,99.88,30.63,4.46,36.29,17.67,59.35,13.76
1,Istanbul,Turkey,2023-02-16,50.63,97.39,48.14,8.71,3.40,144.16,3.46,67.51,6.36
2,Rio de Janeiro,Brazil,2023-11-13,130.21,57.22,98.51,9.92,0.12,179.31,25.29,29.30,12.87
3,Mumbai,India,2023-03-16,119.70,130.52,10.96,33.03,7.74,38.65,23.15,99.97,7.71
4,Paris,France,2023-04-04,55.20,36.62,76.85,21.85,2.00,67.09,16.02,90.28,14.16

In [5]:
#last 5 rows
df.tail()

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
9995,Johannesburg,South Africa,2023-09-16,147.85,184.34,90.33,34.93,2.81,191.45,-1.92,65.22,15.48
9996,Berlin,Germany,2023-12-05,12.22,121.49,49.04,5.66,2.10,184.56,-9.81,12.16,10.75
9997,Moscow,Russia,2023-11-26,44.07,143.62,8.41,32.58,0.69,167.68,39.35,53.95,4.56
9998,Berlin,Germany,2023-02-03,67.43,96.79,43.23,29.19,6.01,148.50,26.21,58.54,2.71
9999,Bangkok,Thailand,2023-06-13,16.34,28.80,50.48,21.20,0.49,17.41,2.50,66.05,5.01

In [8]:
# shows rows and columns count
df.shape

(10000, 12)

In [9]:
# shows all columns
df.columns

Index(['City', 'Country', 'Date', 'PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'O3',
       'Temperature', 'Humidity', 'Wind Speed'],
      dtype='object')

In [10]:
#shows datatypes,null values, memmory usage
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   City         10000 non-null  object
 1   Country      10000 non-null  object
 2   Date         10000 non-null  object
 3   PM2.5        10000 non-null  float64
 4   PM10         10000 non-null  float64
 5   NO2          10000 non-null  float64
 6   SO2          10000 non-null  float64
 7   CO           10000 non-null  float64
 8   O3           10000 non-null  float64
 9   Temperature  10000 non-null  float64
 10  Humidity     10000 non-null  float64
 11  Wind Speed   10000 non-null  float64
dtypes: float64(9), object(3)
memory usage: 937.6+ KB

In [11]:
#give statistics for numeric values
df.describe()

,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000
mean,77.448439,104.438161,52.198649,25.344490,5.047984,106.031643,14.89715,55.078579,10.231636
std,41.927871,55.062396,27.320490,14.091194,2.852625,55.081345,14.44380,25.982232,5.632628
min,5.020000,10.000000,5.010000,1.000000,0.100000,10.040000,-10.00000,10.010000,0.500000
25%,41.185000,57.137500,28.347500,13.190000,2.560000,58.380000,2.25750,32.527500,5.290000
50%,77.725000,103.690000,52.100000,25.350000,5.090000,106.055000,14.75500,55.080000,10.260000
75%,113.392500,152.265000,75.705000,37.500000,7.480000,153.982500,27.38250,77.442500,15.070000
max,149.980000,200.000000,100.000000,49.990000,10.000000,200.000000,40.00000,99.990000,20.000000

In [12]:
#give summary of all columns
df.describe(include="all")

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
count,10000,10000,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000
unique,20,19,336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Mumbai,USA,2023-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,540,962,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,77.448439,104.438161,52.198649,25.344490,5.047984,106.031643,14.89715,55.078579,10.231636
std,NaN,NaN,NaN,41.927871,55.062396,27.320490,14.091194,2.852625,55.081345,14.44380,25.982232,5.632628
min,NaN,NaN,NaN,5.020000,10.000000,5.010000,1.000000,0.100000,10.040000,-10.00000,10.010000,0.500000
25%,NaN,NaN,NaN,41.185000,57.137500,28.347500,13.190000,2.560000,58.380000,2.25750,32.527500,5.290000
50%,NaN,NaN,NaN,77.725000,103.690000,52.100000,25.350000,5.090000,106.055000,14.75500,55.080000,10.260000
75%,NaN,NaN,NaN,113.392500,152.265000,75.705000,37.500000,7.480000,153.982500,27.38250,77.442500,15.070000
max,NaN,NaN,NaN,149.980000,200.000000,100.000000,49.990000,10.000000,200.000000,40.00000,99.990000,20.000000

In [13]:
#check null values astrue/false
df.isnull()

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False

In [14]:
#count missing values column vise
df.isnull().sum()

City           0
Country        0
Date           0
PM2.5          0
PM10           0
NO2            0
SO2            0
CO             0
O3             0
Temperature    0
Humidity       0
Wind Speed     0
dtype: int64

In [15]:
#show missing values percentage
df.isnull().mean() * 100

City           0.0
Country        0.0
Date           0.0
PM2.5          0.0
PM10           0.0
NO2            0.0
SO2            0.0
CO             0.0
O3             0.0
Temperature    0.0
Humidity       0.0
Wind Speed     0.0
dtype: float64

In [46]:
#new testing on emp data
#read cs file
df = pd.read_csv("employee_data.csv")
#basic dataframe checking
#print all data
df
#first 5 rows
df.head()
#last five rows
df.tail()
#shows row and column
df.shape
#show all columns name
df.columns
#Shows datatype, null values, memory usage.
df.info()
#Gives statistics for numeric columns.
df.describe()
#Gives summary for all columns.
df.describe(include="all")


#checking null values
#check missing cvalues as T/F
df.isnull()
#Counts missing values column-wise.
df.isnull().sum()
#Shows missing value percentage.
df.isnull().mean() * 100



#handle null values
#Removes rows having any null value.
df.dropna()

#Fill all null values with specific value
df = df.fillna("NAN")
df




#Check duplicate values
#Returns True for duplicate rows.
df.duplicated()
#Counts duplicate rows.
df.duplicated().sum()
#drop duplicated rows
df = df.drop_duplicates()
df


#selects first row by index position.
df.iloc[0]
# #Selects first 5 rows.
df.iloc[0:5]
# #Selects row by label index.
df.loc[0]


df.to_json("cleaned_employee_data.json")
df_json = pd.read_json("cleaned_employee_data.json")
print(df)


import json

with open("cleaned_employee_data.json", "r") as file:
    data = json.load(file)

print(json.dumps(data, indent=4))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       11 non-null     int64
 1   name     10 non-null     object
 2   age      8 non-null      float64
 3   country  10 non-null     object
 4   gender   10 non-null     object
 5   income   10 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 660.0+ bytes
    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NAN  Canada   Female  62000.0
3    3          Alex   NAN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NAN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NAN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NAN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NAN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NAN  58000.0
{
    "id": {
        "0": 1,
        "2": 2,
        "3": 3,
        "4": 4,
        "5": 5,
        "6": 6,
        "7": 7,
        "8": 8,
        "9": 9,
        "10": 10
    },
    "name": {
        "0": "John Doe",
        "2": "Jane Smith",
        "3": "Alex",
        "4": "Maria Garcia",
        "5": "Li Wei",
        "6": "NAN",
        "7": "Ahmed Khan",
        "8": "Rachel Lee",
        "9": "Carlos Ruiz",
        "10": "Emily Davis"
    },
    "age": {
        "0": 29.0,
        "2": "NAN",
        "3": "NAN",
        "4": 34.0,
        "5": 27.0,
        "6": 45.0,
        "7": 38.0,
        "8": 29.0,
        "9": "NAN",
        "10": 31.0
    },
    "country": {
        "0": "USA",
        "2": "Canada",
        "3": "USA",
        "4": "Spain",
        "5": "China",
        "6": "India",
        "7": "NAN",
        "8": "USA",
        "9": "Mexico",
        "10": "USA"
    },
    "gender": {
        "0": "Male",
        "2": "Female",
        "3": "Unknown",
        "4": "Female",
        "5": "Male",
        "6": "Female",
        "7": "Male",
        "8": "Female",
        "9": "Male",
        "10": "NAN"
    },
    "income": {
        "0": 55000.0,
        "2": 62000.0,
        "3": 47000.0,
        "4": "NAN",
        "5": 51000.0,
        "6": 73000.0,
        "7": 68000.0,
        "8": 62000.0,
        "9": 45000.0,
        "10": 58000.0
    }
}